// =============================================================================
// lib/api/mockPrograms.ts
// Dados simulados (Mock) para as configurações visuais dos programas ativos.
// Usado como fallback quando a API do backend estiver indisponível.
// =============================================================================

import { ProgramUIConfig } from "@/types/program";

export const MOCK_PROGRAMS: Record<string, ProgramUIConfig> = {
  "mcmv-far": {
    id: "mcmv-far" as any,
    name: "Minha Casa Minha Vida — FAR",
    slug: "mcmv-far",
    theme: {
      primaryColor: "#003366",
      accentColor: "#eab308",
      sidebarColor: "#0f172a",
      logoUrl: "",
      shortName: "MCMV-FAR",
    },
    enabledSections: {
      cadastro: true,
      classificacao: true,
      sorteio: true,
      suplencia: true,
      convocacao: true,
      empreendimentos: true,
      unidades: true,
      auditoria: true,
      relatorios: true,
      integracaoCadUnico: true,
      cotasVagas: true,
      prazosProcessuais: true,
    },
    formType: "family",
    labels: {
      beneficiario: "Candidato",
      unidade: "Unidade",
      cadastro: "Inscrição",
      classificacao: "Classificação",
      empreendimento: "Empreendimento",
    },
  },
  "cdru": {
    id: "cdru" as any,
    name: "Concessão de Direito Real de Uso (CDRU)",
    slug: "cdru",
    theme: {
      primaryColor: "#0d5c3a",
      accentColor: "#84cc16",
      sidebarColor: "#0b2e1e",
      logoUrl: "",
      shortName: "CDRU",
    },
    enabledSections: {
      cadastro: true,
      classificacao: true,
      sorteio: false,
      suplencia: true,
      convocacao: true,
      empreendimentos: true,
      unidades: true,
      auditoria: true,
      relatorios: true,
      integracaoCadUnico: false,
      cotasVagas: false,
      prazosProcessuais: true,
    },
    formType: "property",
    labels: {
      beneficiario: "Beneficiário",
      unidade: "Lote",
      cadastro: "Cadastro",
      classificacao: "Hierarquização",
      empreendimento: "Área de Uso",
    },
  },
  "reurb": {
    id: "reurb" as any,
    name: "Regularização Fundiária Urbana (REURB)",
    slug: "reurb",
    theme: {
      primaryColor: "#7c3aed",
      accentColor: "#a78bfa",
      sidebarColor: "#2e1065",
      logoUrl: "",
      shortName: "REURB",
    },
    enabledSections: {
      cadastro: true,
      classificacao: true,
      sorteio: false,
      suplencia: false,
      convocacao: true,
      empreendimentos: false,
      unidades: true,
      auditoria: true,
      relatorios: true,
      integracaoCadUnico: true,
      cotasVagas: false,
      prazosProcessuais: true,
    },
    formType: "family",
    labels: {
      beneficiario: "Requerente",
      unidade: "Lote Regularizado",
      cadastro: "Requerimento",
      classificacao: "Ordem de Prioridade",
      empreendimento: "Núcleo Urbano",
    },
  },
  "cohab-social": {
    id: "cohab-social" as any,
    name: "COHAB Social — Locação Acessível",
    slug: "cohab-social",
    theme: {
      primaryColor: "#0369a1",
      accentColor: "#38bdf8",
      sidebarColor: "#082f49",
      logoUrl: "",
      shortName: "COHAB-SOCIAL",
    },
    enabledSections: {
      cadastro: true,
      classificacao: true,
      sorteio: true,
      suplencia: true,
      convocacao: true,
      empreendimentos: true,
      unidades: true,
      auditoria: true,
      relatorios: true,
      integracaoCadUnico: true,
      cotasVagas: true,
      prazosProcessuais: true,
    },
    formType: "family",
    labels: {
      beneficiario: "Locatário",
      unidade: "Imóvel Social",
      cadastro: "Inscrição",
      classificacao: "Lista de Espera",
      empreendimento: "Residencial",
    },
  },
};
